# Generated by Django 3.0.6 on 2020-06-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latihan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latihan',
            name='total_waktu',
            field=models.CharField(default='5-12 menit/hari', max_length=255),
            preserve_default=False,
        ),
    ]
